version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tenpo-postgres
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: tenpo_user
      POSTGRES_PASSWORD: tenpo_password
    ports:
      - "5435:5432"
    networks:
      - tenpo-net

  redis:
    image: redis:7
    container_name: tenpo-redis
    ports:
      - "6379:6379"
    networks:
      - tenpo-net

  app:
    image: tenpo-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tenpo_db
      SPRING_DATASOURCE_USERNAME: tenpo_user
      SPRING_DATASOURCE_PASSWORD: tenpo_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - tenpo-net

networks:
  tenpo-net:
    driver: bridge
