spring:
  application:
    name: prueba
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5435/tenpo_db
    username: tenpo_user
    password: tenpo_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  server:
    port: 8080

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
